server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth
          uri: ${URL_AUTH:http://auth-service:8080}
          predicates:
            - Path=/auth/**
        - id: orders
          uri: ${URL_ORDER:http://order-service:8081}
          predicates:
            - Path=/orders/**
        - id: payments
          uri: ${URL_PAYMENT:http://payment-service:8082}
          predicates:
            - Path=/payments/**
        - id: search
          uri: ${URL_SEARCH:http://search-service:8083}
          predicates:
            - Path=/search/**
        - id: ai
          uri: ${URL_AI:http://ai-service:8084}
          predicates:
            - Path=/ai/**

management:
  endpoints.web.exposure.include: health,info
