server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: payment-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/payments_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9093}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP:payment-service}
      auto-offset-reset: earliest
    producer:
      acks: all
    properties:
      spring.json.trusted.packages: "*"

management:
  endpoints.web.exposure.include: health,info,metrics,env
  endpoint.health.show-details: always

app:
  topics:
    order: ${ORDER_TOPIC:order.events}
    payment: ${PAYMENT_TOPIC:payment.events}
