server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: search-service

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://elasticsearch:9200}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9093}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP:search-service}
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: "*"

management:
  endpoints.web.exposure.include: health,info,metrics,env
  endpoint.health.show-details: always

app:
  topics:
    order: ${ORDER_TOPIC:order.events}
  elastic:
    index:
      orders: ${ES_INDEX_ORDERS:orders}
